name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze
      - name: Test
        run: |
          export SENTRY_KEY=${{ secrets.SENTRY_KEY }}
          export SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
          dart test